---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Files Management:
    - Filebrowser:
        icon: filebrowser.png
        href: http://192.168.1.20:8080/
        description: 

- What to see:
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://192.168.1.20:5055/
        description: 
    - Watcharr:
        icon: watcharr.png
        href: http://192.168.1.20:3080/
        description:
        
- Torrents:
    - Transmission:
        icon: transmission.png
        href: http://192.168.1.20:9091/
        description: 
    - Nginx:
        icon: nginx.png
        href: http://192.168.1.20:9999/
        description:
        
- Indexers:
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.1.20:8989/
        description: TV Series
    - Radarr:
        icon: radarr.png
        href: http://192.168.1.20:7878/
        description: Movies
    - Lidarr:
        icon: lidarr.png
        href: http://192.168.1.20:8686/
        description: Songs

- Resolvers:
    - Flaresolverr:
        icon: flaresolverr.png
        href: http://192.168.1.20:8191/
        description: 
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.1.20:9696/
        description:
    - YT-DL:
        icon: youtube.png
        href: http://192.168.1.20:8998/
        description:
        
- Players:
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.1.20:8096/
        description: Video Player
    - Navidrome:
        icon: navidrome.png
        href: http://192.168.1.20:4533/
        description: Songs Player
